Q1. Vectorized Linear Model

Given dataset:
X = [1, 2, 3, 4, 5]
y = [3, 5, 7, 9, 11]

Model equation:
y = wX + b

Tasks:
1) Compute weight using:
w = sum(X*y) / sum(X^2)
2) Compute bias:
b = mean(y) − w * mean(X)
3) Predict y for X = [6,7,8]
4) Compute Mean Squared Error:
MSE = (1/n) * Σ (y_true − y_pred)^2

In [ ]:
import numpy as np
import pandas as pd

data={
    "X":[1,2,3,4,5],
    "y":[3,5,7,9,11]
}

df=pd.DataFrame(data)
df

#1.computing weight:

w=np.sum(df["X"]*df["y"])/np.sum(df["X"]**2)
print("Weight:",w)

#2. computing bias:

b=np.mean(df["y"])-w*np.mean(df["X"])
print("Bias:",b)

#3.predicting y for X=[6,7,8]:

X_new=np.array([6,7,8])
y_pred=w*X_new+b
print("Predicted y:",y_pred)

#4. computing Mean Squared Error(MSE):
y_train_pred=w*df["X"]+b
mse=np.mean((df["y"]-y_train_pred)**2)
print("MSE:",mse)










Bias: 0.18181818181818166
Predicted y: [13.81818182 16.09090909 18.36363636]
MSE: 0.1487603305785127


Q2. Normalization & Covariance
Given matrix:

A =
[50 60 70]
[60 65 80]
[55 62 75]

Tasks:
1) Normalize each column:
X_norm = (X − μ) / σ
2) Compute covariance matrix:
Cov(X) = (1/(n−1)) * (X^T * X)
3) Identify most correlated feature pair

In [ ]:
import numpy as np
import pandas as pd
A = np.array([[50, 60, 70], [60, 65, 80], [55, 62, 75]])

# 1. Normalizing each column: X_norm = (X - μ) / σ
n = A.shape[0]
mu = np.mean(A, axis=0)
sigma = np.std(A, axis=0)
A_norm = (A - mu) / sigma
A_norm

# 2. Computing covariance matrix:
# First, center the data: X - μ
A_centered = A - mu
cov_matrix = (1 / (n - 1)) * (A_centered.T@A_centered)
cov_matrix

# 3. Identifing most correlated feature pair:
corr_matrix = np.corrcoef(A, rowvar=False)
corr_matrix


array([[1.        , 0.99339927, 1.        ],
       [0.99339927, 1.        , 0.99339927],
       [1.        , 0.99339927, 1.        ]])

Q3. Advanced GroupBy Analytics

Sales Data Columns:

Date, Region, Product, Revenue

Tasks:
1) Convert Date to datetime
2) Compute total revenue per Region
3) Find top Product per Region (highest mean revenue)
4) Rank regions based on total revenue

In [ ]:
import numpy as np
import pandas as pd

df=pd.DataFrame({
    "Date":["2025-01-01","2025-02-01","2025-03-01","2025-04-01","2025-05-01","2025-06-01"],
    "Region":["Bagmati","Koshi","Lumbini","Koshi","Bagmati","Koshi"],
    "Product":["TV","Laptop","Laptop","Mobile","TV","Mobile"],
    "Revenue":[100000,150000,200000,250000,300000,350000]
})

#1.converting date to datetime:

df["Date"]=pd.to_datetime(df["Date"])
df["Date"]

#2.computing total revenue per region:

#df.groupby("Region")["Revenue"].sum()

#3.finding top product per Region(highest mean revenue):

#df.groupby(["Product","Region"])["Revenue"].mean().groupby("Region").idxmax()

#4.ranking regions based on total revenue:

df.groupby("Region")["Revenue"].sum().rank(ascending=True)



,Revenue
Region,
Bagmati,2.0
Koshi,3.0
Lumbini,1.0


Q4. Merge + Business Logic

Customers: CustomerID, Name, City

Orders: CustomerID, Amount, Date

Tasks:
1) Left join tables
2) Compute total spending per customer
3) Label customer tier:
If spending ≥ 1000 → 'Premium'
Else → 'Standard'
4) Find city with highest average spending

In [ ]:
import numpy as np
import pandas as pd

Customers=pd.DataFrame({
    "CustomerID":[101,102,103],
    "Name":["Milan","Sujan","Balkrishna"],
    "City":["Kathmandu","Lalitpur","Okhaldhunga"]

})
Orders=pd.DataFrame({
    "CustomerID":[101,103,102],
    "Amount":[1000,2000,500],
    "Date":["2026-02-01","2026-02-02","2026-02,03"]
})

#1.left join table:

#pd.merge(Customers,Orders,on="CustomerID",how="left")

#2.total spending per customer:

#df=pd.merge(Customers,Orders,on="CustomerID",how="left")
#df.groupby("Name")["Amount"].sum()

#3.leveling customer tier:

df=pd.merge(Customers,Orders,on="CustomerID",how="left")
df["Tier"]=df["Amount"].apply(lambda Amount:"Premium"if Amount>1000 else "Standard")
df["Tier"]

#4.city with highest average spending:

df=pd.merge(Customers,Orders,on="CustomerID",how="left")
df.groupby("City")["Amount"].mean().idxmax()

0    Standard
1    Standard
2     Premium
Name: Tier, dtype: object


'Okhaldhunga'

Q5. Time-Based Filtering

Transactions: Date, Amount

Tasks:
1) Convert Date column to datetime
2) Filter transactions after 2024-01-05
3) Compute daily total spending
4) Find day with maximum expenditure

In [ ]:
import numpy as np
import pandas as pd

df=pd.DataFrame({
    "Date":["2022-01-05","2024-01-05","2025-01-05","2026-01-05"],
    "Amount":[10000,20000,30000,40000]
})

#1.converting Date column to datetime:

df["Date"]=pd.to_datetime(df["Date"])
df["Date"]

#2.filtering transaction after 2024-01-05:

filtered_df=df[df["Date"]>"2024-01-05"]
filtered_df

#3.daily total spending:

daily_spending=filtered_df.groupby("Date")["Amount"].sum()
daily_spending

#4.day with maximum expenditure:

maximum_exp_day=daily_spending.idxmax()
maximum_exp_day

maximum_exp_amount=daily_spending.max()
maximum_exp_amount



40000